# Generated by Django 3.2.4 on 2023-02-03 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=1000, null=True, verbose_name='Name')),
                ('password', models.CharField(blank=True, db_column='password', max_length=1000, null=True, verbose_name='password')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
